"""Deterministic SQL Safety issue codes for Query Template validation."""

from __future__ import annotations


class SqlSafetyIssueCode:
    PARSE_ERROR = "SQL_SAFETY_PARSE_ERROR"
    MULTIPLE_STATEMENTS = "SQL_SAFETY_MULTIPLE_STATEMENTS"
    STATEMENT_NOT_ALLOWED = "SQL_SAFETY_STATEMENT_NOT_ALLOWED"
    FOR_UPDATE_FORBIDDEN = "SQL_SAFETY_FOR_UPDATE_FORBIDDEN"
    SELECT_INTO_FORBIDDEN = "SQL_SAFETY_SELECT_INTO_FORBIDDEN"
    FORBIDDEN_CONSTRUCT = "SQL_SAFETY_FORBIDDEN_CONSTRUCT"
    UNDECLARED_PARAMETER = "SQL_SAFETY_UNDECLARED_PARAMETER"
    UNUSED_DECLARED_PARAMETER = "SQL_SAFETY_UNUSED_DECLARED_PARAMETER"
    POSITIONAL_PARAMETER_FORBIDDEN = "SQL_SAFETY_POSITIONAL_PARAMETER_FORBIDDEN"
    DYNAMIC_IDENTIFIER_FORBIDDEN = "SQL_SAFETY_DYNAMIC_IDENTIFIER_FORBIDDEN"
